### ISSUE TITLE
"Import settings expired" message.

### ISSUE THREAD

**Issue by jeremyboggs** [omeka/plugin-CsvImport#27]
After several attempts to import with the current master branch in Omeka 2.0, I keep getting "Import settings expired. Please try again." I'm able to fill out the first screen, and proceed to mapping fields from the examples pulled from my CSV file, but once I submit that second form, I get redirected back to the index, with that flash message at the top.

**Comment by zerocrates** [comment]
This bug should be fixed on current Omeka versions: the underlying cause was invalid UTF-8 data causing sessions to be truncated when stored in the database.
