### ISSUE TITLE
Improve "stopped import" log line

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-CsvImport#69]
The log is useful to show the error that stopped the import, but we should include other error data beyond just the message (like filename and line number) to make it better.

**Comment by patrickmj** [comment]
Is this what you had in mind? https://github.com/omeka/plugin-CsvImport/commit/bd9cccbd0d58ad2143c4b907f63cf6583eb78bbb 

I'm guessing that this came from some kind of debugging situation?

**Comment by zerocrates** [comment]
yeah pretty much.

Context is just that recent forum post, the getid3 error is logged but not with those extra details.
