### ISSUE TITLE
Look into skipping empty lines

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-CsvImport#71]
I've seen a couple reports that CSVImport attempts to process empty lines, which can cause the import to drag on forever. Might be worth seeing if there's a way to avoid that problem.

See, e.g. https://twitter.com/patrick_mj/status/917364545349472256

**Comment by Daniel-KM** [comment]
I added a check to skip empty rows (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/dfac9b1a4394e2cb36431bfe501fec1bdfd81c3d).
