### ISSUE TITLE
Error importing csv file

### ISSUE THREAD

**Issue by AngeloVenera** [omeka/plugin-CsvImport#74]
Hi everyone, I have the following error during the loading phase of a txt file "Your file is incorrectly formatted. Header row contains 18 unique column name(s) for 31 columns. Please ensure that all column names are unique.", hereinafter the contents of the file:

Dublin Core:Tipo#Dublin Core:Data#Dublin Core:Lingua#Dublin Core:Autore#Zotero:ISSN#Zotero:ISBN#Zotero:ISSN#Zotero:DOI#Dublin Core:Alternative Title#Dublin Core:Alternative Title#Dublin Core:Titolo#Dublin Core:Alternative Title#Zotero:Edition#Dublin Core:Spatial Coverage#Dublin Core:Editore#Dublin Core:Formato#Zotero:Series#Dublin Core:Descrizione#Dublin Core:Descrizione#Dublin Core:Soggetto#Dublin Core:Soggetto#Dublin Core:Soggetto#Dublin Core:Soggetto#Dublin Core:Altri autori#Dublin Core:Altri autori#Dublin Core:Altri autori#Dublin Core:Alternative Title#Dublin Core:Alternative Title#Zotero:Series#Dublin Core:Relazione#Dublin Core:Relazione
"a"#"2018"#"eng"#"Gottschalk, Petter, 1950-"#"9783319689166 (electronic bk.)""3319689169 (electronic bk.)""9783319689159"#"9783319689159"##"10.1007/978-3-319-68916-6 doi"###"Investigating white-collar crime [electronic resource] : evaluation of fraud examinations / Petter Gottschalk."###"Cham :"#"Springer International Publishing,"#"1 online resource (xiv, 265 p.) : ill."##"Title from PDF of title page (viewed, Apr. 12, 2019)"#"This book examines internal fraud investigations in public and private organizations. It provides a theoretical framework of white-collar crime and convenience theory, to examine a number of case studies, including some cases brought to light by the Panama Papers.Investigating white-collar crime is distinguished from other types of crime by: concealment of the crime rather than the criminal, victims who may be unaware of the crime and not directly visible to the criminal, and the resources available to suspects. It requires a unique strategy and a unique set of tools.This work provides insight into a number of internal investigation reports that are normally not publicly available. It will be of interest to researchers in criminology and criminal justice, particularly with an interest in white collar crime and corruption, as well as related fields such as business, management, economics, and public administration"####"White collar crime.""Fraud investigation."##"SpringerLink (Online service)"#####"https://link.springer.com/book/10.1007/978-3-319-68916-6"#"Publisher's Web site. Access restricted to the University of Catania community"

Is there a limit regarding the length of the header line? As you can see there are 31 headings for 31 data columns.

Thanks Angel

**Comment by zerocrates** [comment]
The issue here is that the plugin wants all your header names to be different from each other.
